// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: deleteuser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteAllChirpsFromUser = `-- name: DeleteAllChirpsFromUser :exec
DELETE FROM chirps WHERE user_id = $1
`

func (q *Queries) DeleteAllChirpsFromUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllChirpsFromUser, userID)
	return err
}
